module.exports = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "secondary-fixed-dim": "#adc6ff",
                "secondary-fixed": "#d8e2ff",
                "surface-bright": "#fbf8fc",
                "on-primary": "#ffffff",
                "primary-container": "#6063ee",
                "error-container": "#ffdad6",
                "inverse-primary": "#c0c1ff",
                "secondary-container": "#2170e4",
                "on-tertiary-fixed": "#301400",
                "surface-container-highest": "#e4e1e6",
                "on-background": "#1b1b1e",
                "tertiary-fixed": "#ffdcc5",
                "on-secondary-fixed-variant": "#004395",
                "on-primary-fixed": "#07006c",
                "on-primary-container": "#fffbff",
                "surface-container-high": "#eae7eb",
                error: "#ba1a1a",
                secondary: "#0058be",
                surface: "#fbf8fc",
                "on-error-container": "#93000a",
                "on-primary-fixed-variant": "#2f2ebe",
                "outline-variant": "#c7c4d7",
                "on-tertiary-fixed-variant": "#703700",
                "on-surface-variant": "#464554",
                "on-secondary-fixed": "#001a42",
                "inverse-on-surface": "#f3f0f4",
                "surface-tint": "#494bd6",
                "surface-dim": "#dcd9dd",
                "surface-container": "#f0edf1",
                "primary-fixed-dim": "#c0c1ff",
                "on-surface": "#1b1b1e",
                outline: "#767586",
                "on-tertiary-container": "#fffbff",
                "surface-variant": "#e4e1e6",
                "tertiary-container": "#b55d00",
                "surface-container-low": "#f6f2f7",
                tertiary: "#904900",
                "surface-container-lowest": "#ffffff",
                "on-tertiary": "#ffffff",
                "on-error": "#ffffff",
                background: "#fbf8fc",
                "primary-fixed": "#e1e0ff",
                "inverse-surface": "#303033",
                "on-secondary": "#ffffff",
                "tertiary-fixed-dim": "#ffb783",
                primary: "#4648d4",
                "on-secondary-container": "#fefcff",
            },
            borderRadius: {
                DEFAULT: "0.125rem",
                lg: "0.25rem",
                xl: "0.5rem",
                full: "0.75rem",
            },
            spacing: {
                "unit-8": "2rem",
                "unit-3": "0.75rem",
                "unit-1": "0.25rem",
                gutter: "1rem",
                "margin-mobile": "1rem",
                "unit-6": "1.5rem",
                base: "4px",
                "unit-4": "1rem",
                "margin-desktop": "2rem",
                "unit-2": "0.5rem",
            },
            fontFamily: {
                display: ["Geist"],
                body: ["Geist Sans", "sans-serif"],
                headline: ["Geist Sans", "sans-serif"],
                label: ["Geist Sans", "sans-serif"],

                "body-sm": ["Geist Sans", "sans-serif"],
                "body-md": ["Geist Sans", "sans-serif"],

                "headline-sm": ["Geist Sans", "sans-serif"],
                "headline-lg": ["Geist Sans", "sans-serif"],
                "headline-lg-mobile": ["Geist Sans", "sans-serif"],

                "label-caps": ["Geist Sans", "sans-serif"],

                "mono-sm": ["Geist Mono", "monospace"],
                "mono-md": ["Geist Mono", "monospace"],
            },
            fontSize: {
                display: [
                    "36px",
                    {
                        lineHeight: "1.2",
                        letterSpacing: "-0.02em",
                        fontWeight: "600",
                    },
                ],
                "headline-sm": [
                    "18px",
                    { lineHeight: "1.4", fontWeight: "500" },
                ],
                "headline-lg": [
                    "24px",
                    {
                        lineHeight: "1.3",
                        letterSpacing: "-0.01em",
                        fontWeight: "600",
                    },
                ],
                "mono-sm": ["12px", { lineHeight: "1.6", fontWeight: "400" }],
                "mono-md": ["13px", { lineHeight: "1.6", fontWeight: "400" }],
                "label-caps": [
                    "11px",
                    {
                        lineHeight: "1",
                        letterSpacing: "0.05em",
                        fontWeight: "600",
                    },
                ],
                "headline-lg-mobile": [
                    "20px",
                    { lineHeight: "1.3", fontWeight: "600" },
                ],
                "body-sm": ["13px", { lineHeight: "1.5", fontWeight: "400" }],
                "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
            },
        },
    },
};
